
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Wissensbasis
logo: /assets/img/FDMScouts_nrw_Logo.png
description: Fragen und Antworten für den Einstieg in das Thema Forschungsdatenmanagement - für das Infrastrukturpersonal.
show_downloads: true
google_analytics:
